### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by mithro** [The-OpenROAD-Project/OpenROAD-Cloud#1]
All published code should have a LICENSE file.

See https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by abdelrahmanhosny** [comment]
Hi @mithro
Thank you for sharing this. It will be addressed before the official release in July 2019.

**Comment by abdelrahmanhosny** [comment]
Thanks again @mithro for pointing out to this. License is added.
